### ISSUE TITLE
Edit message popup removes trailing space while editing

### ISSUE THREAD

**Issue by RemiBardon** [prose-im/prose-app-web#130]
When deleting the last character after a space in the edit message popup, it also deletes the space, which is confusing. I also had issues editing messages before updating (loosing focus, missing characters), but I didn't try reproducing so I'll report it later if the issue persists.

https://github.com/user-attachments/assets/71732506-c56b-4580-bb34-92f071f869af

I'm using Prose `Version 0.5.0 (20240803.100136)`

**Comment by poVoq** [comment]
Did you check that this isn't a mobile on-screen keyboard issue? Many have odd behaviour like that.

**Comment by RemiBardon** [comment]
It was on my Mac, why would I have mobile on-screen issues?

**Comment by poVoq** [comment]
Just double checking, because the screenshot you posted looks like it could be from a mobile screen.

But these kind of "smart" input improvements are also making their way to desktop computers. On Microsoft Office 365 for example you need to check these days that it actually put what you wrote and not something their algorithm thought you intended to write.

**Comment by valeriansaliou** [comment]
This was an issue on our side, this is fixed now.
