### ISSUE TITLE
Use name embedded in Message for displaying a sender

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#27]
Instead of taking `Message::from` and performing a lookup to retrieve the name, use `Message::user::name` instead.

```ts
export class Message {
  free(): void;

  readonly archiveId: string | undefined;
  readonly content: string;
  readonly date: string;
  readonly from: string;

  id?: string;

  readonly metas: string | undefined;
  readonly reactions: Reaction[];
  readonly text: string;
  readonly timestamp: Date;
  readonly type: string;
  readonly user: MessageSender;
}

export class MessageSender {
  free(): void;

  readonly jid: string;
  readonly name: string;
}
```

**Comment by valeriansaliou** [comment]
I'm actually using the `name` from `participants`, couldn't you maintain this name there and notify when participants data changed so that I can notify the views?

That'd be much cleaner on my end, rather than relying on 2 data sources, since I need to show the participants list on the right details sidebar anyway, whether I received a message from this participant or not, therefore I need to know the name in advance before receiving any message from this participant.

**Comment by valeriansaliou** [comment]
Adding to my last comment, it’d also be cleaner for the views themselves, since the way I’ve designed them is that names are set per JID, and not per message.

If the name changes for a JID then I simply need to call a method to update the views store and set the new name, which will trigger a re-render of all messages in view for that specific JID.

I would therefore rather avoid having two ways to set names in the views, ie. the traditional global per-JID way, and the new per-message way.

**Comment by nesium** [comment]
I saw that in the web app when you select a participant it selects the 1:1 conversation with the selected participant. I've changed `ParticipantInfo.jid` to be optional…

```ts
export class ParticipantInfo {
  readonly affiliation: RoomAffiliation;
  readonly availability: Availability;
  readonly isSelf: boolean;
  readonly jid: JID | undefined;
  readonly name: string;
}
```

The reason is that there is no guarantee that we have a real jid for a participant. It is only available in non-anonymous rooms. 

What could also happen is that we load a message via MAM from someone who no longer is a participant of a room. In this case we might or might not have the real jid (and thus contact info) available depending on the room configuration, but they won't be available in the participants array in any event. We could insert a tombstone - once the message is loaded - but I'm not sure that this is the better solution.

**Comment by valeriansaliou** [comment]
Checking the JIDs that are provided in the `message.user` object, they are not sufficient for me to properly inject a MUC message the view when it just came, ie. it's new. All I get is the MUC JID, with no resource, which is not sufficient for me to acquire the user avatar. The name is correct though.

However, if I reload the Prose app, the same message will come (from MAM?) with the user's private JID, and the same name (which is perfect for me to work with).

Could we make MUC message returned JIDs consistent between history and just-received new messages? I can't seem to work with the `message.user` `MessageSender` object for now...

**Comment by valeriansaliou** [comment]
Ok, made the implementation to hybridate the identify system which goes to the views. If a "global" name is available for a given JID, meaning a name from participants, I'll use this one and prefer it over any name contained in messages for the same JID. If we don't have a global name for the JID, then I'll use the name contained in messages.

The system is efficient and only re-identify in the views when needed, thus only triggering a re-render of updated messages when strictly needed.

I'll be waiting for a fix for the issue described [in the comment above](#issuecomment-1902687570).

**Comment by nesium** [comment]
Received (not loaded from MAM) messages now contain the real jid in `user.jid`. `user.jid` will need to be optional though since this is the same issue as with `ParticipantInfo` where we don't necessarily know the real jid.

**Comment by nesium** [comment]
Done. `Message.from` was removed, `Message.user.jid` is now optional.

**Comment by valeriansaliou** [comment]
Mhhhh all messages sent/received through DMs, whether they are just sent in the same session or restored from MAM, do not hold any `Message.user.jid`, so I cannot insert them. Could you fix this? Also, if possible, never serve a message if you don't know (yet) the JID, since it does not make any sense to serve a message w/ no origin JID.

In case you don't know the real JID for the message sender, eg. in case of an anonymous MUC, at least serve the full MUC JID which helps me distinguish the sending user in the messaging view, eg. `room@muc.server.tld/username`.

**Comment by nesium** [comment]
Sorry about that, I didn't consider the message grouping. Will revert it and fix the remaining bug.

**Comment by valeriansaliou** [comment]
Perfect, I'll implement this later today. Thanks Marc!

**Comment by valeriansaliou** [comment]
Okay, works now.

Last weird thing I've noticed, which causes an issue with message grouping on my side:

- In a channel, as `valerian@prose.org` I send a message
- Immediately upon sending, I receive the `messageAppended` event with JID `valerian@prose.org/someresource` (which is invalid in that case, I don't expect to receive a resource if it's my own private JID)
- Right after, I receive the `messageAppended` event once again, with JID `valerian@prose.org` (which is valid)

Can we make sure the resource part is only sent in `messageAppended` events for MUC rooms where we really do not know the private JID of the person, and thus we have to rely on the MUC JID?

That will fix my issue, I can however already fix it but it implies doing dirty things like cutting the resource part before inserting, when we assume the JID is a private one. I'd really not do that in the app.

**Comment by nesium** [comment]
Alright, this is now fixed as well. 

The problem was that I parsed the sent message in the same way I did with received messages, but it didn't contain all the fields a received (MUC) message would.

The `messagesAppended` event was sent right afterwards when the actual sent message came back from the server (with the server-generated stanzaID). In this case I'm now sending a `messagesUpdated` event instead.

And yes, let's don't add any workarounds that we'd have to replicate in the other client implementations.
