### ISSUE TITLE
Availability of participants not updated in room sidebar

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-app-web#44]
Steps to reproduce:
- Join a MUC room with Prose client
- Join the same room from a different account
- Change availability for second account
- Observe in first client that `roomParticipantsChanged(_client: ProseClient, room: Room)` is called as expected and `room.participants` contains the updated availability

Expected result:
Availability indicator next to participant in right sidebar should reflect new state

Actual result:
Availability indicator doesn't change

After reloading the webpage, the availability indicator show the correct state.

It seems like the left sidebar isn't updated either since I have an open single-user conversation with the same user.

**Comment by valeriansaliou** [comment]
I've ran some tests, and it sounds like a more general issue w/ the management of availabilities from the roster.

Previously, whenever a contact changed their presence, I'd receive a `contactListChanged` event which would prompt me to reload the roster, thus updating the availability to the correct one. Now, I don't receive this event anymore whenever a contact changes their availabilities.

Even if I did, anyways, I think we'd have a problem, since I would need to call `loadContacts` for each presence change, leading to a full roster reload from the server (or maybe not anymore?).

Since I'm using the known global contact presence for room participant presences, over the provided `availability` in the participant informations, only if the participant JID is known and that JID is found in the roster, the left sidebar issue also arises on the right sidebar in the participants list. Overriding the presence component in this right sidebar w/ the `availability` provided in the participants information event effectively fixes the issue. However, I'm not going to change the code here for now, since that's a more general issue we need to fix in the core.

So, this whole thing leads me to wonder if we shouldn't have a way to load all known presences from the core, eg. `loadPresences()`, that would be completely separate from the roster, avoiding a full roster reload everytime I need to update someone's presence on the app, or even if the roster was cached in the core, reloading the whole roster and re-populating the app store would still be heavy.

We could have a selective `contactEntryChanged(jid: JID)` that would only push the changed `Contact` instance. Or, separate presence management from the roster altogether (which would be more complex however). I would lean towards adding a `contactEntryChanged(jid: JID)` delegate event, and probably in the future expanding this improvement to eg. the list of participants, and maybe other similar "an entity in this possibly large list was updated, please reload everything" events.

**Comment by nesium** [comment]
Hey Valerian. Let me address your points one after another…

1. **Events**: The fired events seem right. The web app receives a call to each of `sidebarChanged`, `contactChanged` (with the affected JID) and `roomParticipantsChanged`. I also have unit tests to verify these so they shouldn't have changed, at least very recently.
2. **Global availability lookup**: If this is the behavior that we want we should encode it in the core. I'd prefer it if a) the UI apps were as simple as possible so that b) we don't have to replicate the same behavior in other UI apps. This also makes change and debugging easier because otherwise I have to figure out why a value in the UI doesn't reflect a change in the core.
3. **Roster reload**: The roster is indeed only [loaded once during login](https://xmpp.org/rfcs/rfc6121.html#roster-login). Subsequent calls to `loadContacts` fetch the roster from memory. The roster is of course updated when the server sends changes.
4. **Looking up contact infos**: Where we _do_ have a (N+1) problem however is when resolving the real names for contacts and participants. During testing I have connected to rooms which have 500+ participants, looking up all vCards there might be a bit much. Since my last change in prose-im/prose-core-client#52 I'm only trying to resolve the names of owners, admins and members and also for newly received presences (because I hadn't changed that bit). I'm not sure yet what the right thing to do is there. For such massive rooms the UI kind of breaks as well since you have to scroll a lot.
5. **Fine-grained events**: I agree that the events for lists are a bit heavy (also see above `roomParticipantsChanged` for the rooms with 500+ participants) but were a concession that we wouldn't have to deal with events that were too fine-grained too early.
6. **Event documentation**: Once we agree on the events we should document which part of the UI needs to be refreshed by apps so that they behave consistently. The naming of the events needs to be strict so that we can tell the different concepts of sidebar (always visible), contact list (rarely visible), participants list (often visible) etc. apart. I would also like to see screenshots (or wireframes) in that documentation to make it easy to grasp. The `contactChanged` event is admittedly vague because the concepts emerged over time.

How to proceed?
- If you agree you should use the availability value from the participants for the right sidebar.
- We'd then write another issue in the prose-core repo to use the global availability for participants if available to match the current web app behavior.
- I would would still leave the events as-is for now since fine-grained events could break more easily as long as things are somewhat in flux.

What do you think?

**Comment by valeriansaliou** [comment]
I've finally found out the reason behind the roster not reloading on my side, the reason being that a presence change results in a `sidebarChanged` event being dispatched. Which used to be the case before, however I've refactored the code so that we would not reload the roster in such event, since it's basically a no-op.

This is where the presence would have stopped updating on the app side. I've added a hook to reload the roster in the event we receive a `contactChanged`, which was previously unused on my side, since I was only hooking to `contactListChanged` (which is not fired here). So far so good, it's all fixed.

I've also forced the use of the `participant`-backed availability in the channel/group member list now. The global availability is not used there anymore.

**Comment by valeriansaliou** [comment]
On the fine-grained events, I do agree with you Marc, let's leave this as-is for now, and avoid any kind of premature optimization. We know what to do if we're noticing performance issues in real-world usage scenarios (ie. add fine-grained per-entity events).
